name: Sync with template

on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches:
      - main

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: template-sync
        name: actions-template-sync
        uses: AndreasAugustin/actions-template-sync@v2.2.3
        with:
          source_repo_path: "amdoc-io/amdoc-client-template"
          upstream_branch: "main"
          pr_labels: "automerge"
      - id: automerge
        name: automerge
        if: steps.template-sync.outputs.pull-request-number != ''
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          PULL_REQUEST: "${{ steps.template-sync.outputs.pull-request-number }}"
      - name: feedback
        if: ${{ steps.automerge.outputs.mergeResult == 'merged' }}
        run: |
          echo "Pull request ${{ steps.automerge.outputs.pullRequestNumber }} merged!"
