name: Sync with template

on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches:
      - main
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: template-sync
        name: actions-template-sync
        uses: AndreasAugustin/actions-template-sync@v2.2.3
        with:
          source_repo_path: "amdoc-io/amdoc-client-template"
          upstream_branch: "main"
          pr_labels: "automerge"

  automerge:
    runs-on: ubuntu-latest
    needs: [repo-sync]
    steps:
      - name: automerge
        id: automerge
        uses: pascalgn/automerge-action@v0.16.3
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: feedback
        if: ${{ steps.automerge.outputs.mergeResult == 'merged' }}
        run: |
          echo "Pull request ${{ steps.automerge.outputs.pullRequestNumber }} merged!"
