name: Sync with template

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: actions-template-sync
        uses: AndreasAugustin/actions-template-sync@v2.2.3
        with:
          source_repo: "https://github.com/amdoc-io/amdoc-client-template.git"
          source_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
