name: Sync with template

on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches:
      - main

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: template-sync
        name: actions-template-sync
        uses: AndreasAugustin/actions-template-sync@v2.2.3
        with:
          github_token: ${{ secrets.ACTION_SECRET }}
          source_repo_path: amdoc-io/amdoc-client-template
          upstream_branch: main
          pr_labels: automerge
          is_force_push_pr: true
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.3"
        env:
          GITHUB_TOKEN: "${{ secrets.ACTION_SECRET }}"
          MERGE_LABELS: ""
